/* eslint no-unused-vars: 0 */

const MIRI_EVENTS = {
  LOAD_EXTENSION_INFO: 'LOAD_EXTENSION_INFO',
  REQUEST_TOKEN: 'REQUEST_TOKEN',
  GET_SITE_SETTINGS: 'GET_SITE_SETTINGS',
  SET_SITE_SETTINGS: 'SET_SITE_SETTINGS',
};

const PARSE_ENGINES = [
  {
    key: 'LOCAL_KUROMOJI',
    i18nKey: 'ui_engine_builtin',
  },
  {
    key: 'MIRIGANA_ONLINE',
    i18nKey: 'ui_engine_online',
  },
];

const HIRAGANA_SIZE_PERCENTAGE_KEY = 'HIRAGANA_SIZE_PERCENTAGE';
const HIRAGANA_SIZE_PERCENTAGE_DEFAULT = 50;

const CURRENT_PARSE_ENGINE_KEY = 'miriEngine';
const CURRENT_PARSE_ENGINE_DEFAULT = 'LOCAL_KUROMOJI';

const SITE_RUBY_DISABLED_KEY = 'miriRubyDisabled';
const SITE_RUBY_DISABLED_DEFAULT = false;
